import type { NutritionData } from './types'

export interface DemoProduct {
  product_name: string
  category: string
  nutrition: NutritionData
  brand: string
  image_url: null
}

export const DEMO_PRODUCTS: Record<string, DemoProduct[]> = {
  dairy: [
    {
      product_name: 'Al Ain Full Cream Milk',
      category: 'dairy',
      brand: 'Al Ain',
      image_url: null,
      nutrition: {
        energy_kcal: 61,
        sugars_g: 4.7,
        saturated_fat_g: 2.0,
        sodium_mg: 42,
        protein_g: 3.2,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Rawabi Laban',
      category: 'dairy',
      brand: 'Al Rawabi',
      image_url: null,
      nutrition: {
        energy_kcal: 38,
        sugars_g: 3.5,
        saturated_fat_g: 0.7,
        sodium_mg: 50,
        protein_g: 3.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Almarai Plain Yogurt',
      category: 'dairy',
      brand: 'Almarai',
      image_url: null,
      nutrition: {
        energy_kcal: 73,
        sugars_g: 4.4,
        saturated_fat_g: 2.3,
        sodium_mg: 60,
        protein_g: 5.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Philadelphia Cream Cheese',
      category: 'dairy',
      brand: 'Philadelphia',
      image_url: null,
      nutrition: {
        energy_kcal: 250,
        sugars_g: 3.5,
        saturated_fat_g: 15.0,
        sodium_mg: 490,
        protein_g: 5.5,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Lurpak Unsalted Butter',
      category: 'dairy',
      brand: 'Lurpak',
      image_url: null,
      nutrition: {
        energy_kcal: 740,
        sugars_g: 0.6,
        saturated_fat_g: 52.0,
        sodium_mg: 11,
        protein_g: 0.5,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Kiri Cheese Spread',
      category: 'dairy',
      brand: 'Kiri',
      image_url: null,
      nutrition: {
        energy_kcal: 287,
        sugars_g: 3.0,
        saturated_fat_g: 18.0,
        sodium_mg: 560,
        protein_g: 8.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Activia Stirred Yogurt',
      category: 'dairy',
      brand: 'Activia',
      image_url: null,
      nutrition: {
        energy_kcal: 82,
        sugars_g: 11.5,
        saturated_fat_g: 1.4,
        sodium_mg: 55,
        protein_g: 4.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Ain Fresh Cream',
      category: 'dairy',
      brand: 'Al Ain',
      image_url: null,
      nutrition: {
        energy_kcal: 309,
        sugars_g: 3.0,
        saturated_fat_g: 21.0,
        sodium_mg: 30,
        protein_g: 2.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
  ],

  beverages: [
    {
      product_name: 'Coca-Cola Original',
      category: 'beverages',
      brand: 'Coca-Cola',
      image_url: null,
      nutrition: {
        energy_kcal: 42,
        sugars_g: 10.6,
        saturated_fat_g: 0,
        sodium_mg: 4,
        protein_g: 0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Vimto Fruit Cordial',
      category: 'beverages',
      brand: 'Vimto',
      image_url: null,
      nutrition: {
        energy_kcal: 47,
        sugars_g: 11.3,
        saturated_fat_g: 0,
        sodium_mg: 10,
        protein_g: 0.1,
        fiber_g: 0,
        fruits_veg_percent: 5,
      },
    },
    {
      product_name: 'Al Ain Water',
      category: 'beverages',
      brand: 'Al Ain',
      image_url: null,
      nutrition: {
        energy_kcal: 0,
        sugars_g: 0,
        saturated_fat_g: 0,
        sodium_mg: 6,
        protein_g: 0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Rani Orange Juice',
      category: 'beverages',
      brand: 'Rani',
      image_url: null,
      nutrition: {
        energy_kcal: 50,
        sugars_g: 11.0,
        saturated_fat_g: 0,
        sodium_mg: 5,
        protein_g: 0.3,
        fiber_g: 0.2,
        fruits_veg_percent: 30,
      },
    },
    {
      product_name: 'Red Bull Energy Drink',
      category: 'beverages',
      brand: 'Red Bull',
      image_url: null,
      nutrition: {
        energy_kcal: 46,
        sugars_g: 11.0,
        saturated_fat_g: 0,
        sodium_mg: 80,
        protein_g: 0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Lipton Ice Tea Peach',
      category: 'beverages',
      brand: 'Lipton',
      image_url: null,
      nutrition: {
        energy_kcal: 29,
        sugars_g: 6.7,
        saturated_fat_g: 0,
        sodium_mg: 18,
        protein_g: 0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Barbican Malt Beverage',
      category: 'beverages',
      brand: 'Barbican',
      image_url: null,
      nutrition: {
        energy_kcal: 43,
        sugars_g: 10.0,
        saturated_fat_g: 0,
        sodium_mg: 20,
        protein_g: 0.3,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Mai Dubai Water',
      category: 'beverages',
      brand: 'Mai Dubai',
      image_url: null,
      nutrition: {
        energy_kcal: 0,
        sugars_g: 0,
        saturated_fat_g: 0,
        sodium_mg: 4,
        protein_g: 0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
  ],

  snacks: [
    {
      product_name: "Lay's Classic Chips",
      category: 'snacks',
      brand: "Lay's",
      image_url: null,
      nutrition: {
        energy_kcal: 536,
        sugars_g: 0.5,
        saturated_fat_g: 4.5,
        sodium_mg: 600,
        protein_g: 6.5,
        fiber_g: 4.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'KitKat 4 Finger',
      category: 'snacks',
      brand: 'KitKat',
      image_url: null,
      nutrition: {
        energy_kcal: 518,
        sugars_g: 48.0,
        saturated_fat_g: 16.0,
        sodium_mg: 100,
        protein_g: 6.7,
        fiber_g: 2.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Oreo Original Cookies',
      category: 'snacks',
      brand: 'Oreo',
      image_url: null,
      nutrition: {
        energy_kcal: 480,
        sugars_g: 38.0,
        saturated_fat_g: 8.0,
        sodium_mg: 430,
        protein_g: 4.5,
        fiber_g: 1.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Pringles Original',
      category: 'snacks',
      brand: 'Pringles',
      image_url: null,
      nutrition: {
        energy_kcal: 536,
        sugars_g: 2.5,
        saturated_fat_g: 9.0,
        sodium_mg: 635,
        protein_g: 4.0,
        fiber_g: 3.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Twix Chocolate Bar',
      category: 'snacks',
      brand: 'Twix',
      image_url: null,
      nutrition: {
        energy_kcal: 495,
        sugars_g: 47.0,
        saturated_fat_g: 13.0,
        sodium_mg: 210,
        protein_g: 4.8,
        fiber_g: 1.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: "M&M's Peanut",
      category: 'snacks',
      brand: "M&M's",
      image_url: null,
      nutrition: {
        energy_kcal: 512,
        sugars_g: 49.0,
        saturated_fat_g: 10.0,
        sodium_mg: 45,
        protein_g: 9.5,
        fiber_g: 2.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Doritos Nacho Cheese',
      category: 'snacks',
      brand: 'Doritos',
      image_url: null,
      nutrition: {
        energy_kcal: 496,
        sugars_g: 3.0,
        saturated_fat_g: 3.5,
        sodium_mg: 700,
        protein_g: 6.0,
        fiber_g: 4.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Snickers Bar',
      category: 'snacks',
      brand: 'Snickers',
      image_url: null,
      nutrition: {
        energy_kcal: 488,
        sugars_g: 43.0,
        saturated_fat_g: 9.0,
        sodium_mg: 240,
        protein_g: 8.0,
        fiber_g: 1.5,
        fruits_veg_percent: 0,
      },
    },
  ],

  cereals: [
    {
      product_name: "Kellogg's Corn Flakes",
      category: 'cereals',
      brand: "Kellogg's",
      image_url: null,
      nutrition: {
        energy_kcal: 378,
        sugars_g: 8.0,
        saturated_fat_g: 0.2,
        sodium_mg: 730,
        protein_g: 7.0,
        fiber_g: 3.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Nestle Fitness Original',
      category: 'cereals',
      brand: 'Nestle',
      image_url: null,
      nutrition: {
        energy_kcal: 370,
        sugars_g: 17.0,
        saturated_fat_g: 0.6,
        sodium_mg: 490,
        protein_g: 8.0,
        fiber_g: 7.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Quaker Whole Oats',
      category: 'cereals',
      brand: 'Quaker',
      image_url: null,
      nutrition: {
        energy_kcal: 367,
        sugars_g: 1.0,
        saturated_fat_g: 1.3,
        sodium_mg: 6,
        protein_g: 13.0,
        fiber_g: 10.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Weetabix Original',
      category: 'cereals',
      brand: 'Weetabix',
      image_url: null,
      nutrition: {
        energy_kcal: 362,
        sugars_g: 4.4,
        saturated_fat_g: 0.6,
        sodium_mg: 270,
        protein_g: 11.0,
        fiber_g: 10.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Alpen Muesli No Added Sugar',
      category: 'cereals',
      brand: 'Alpen',
      image_url: null,
      nutrition: {
        energy_kcal: 365,
        sugars_g: 12.0,
        saturated_fat_g: 1.4,
        sodium_mg: 120,
        protein_g: 10.0,
        fiber_g: 7.0,
        fruits_veg_percent: 10,
      },
    },
    {
      product_name: 'Cheerios Original',
      category: 'cereals',
      brand: 'Cheerios',
      image_url: null,
      nutrition: {
        energy_kcal: 372,
        sugars_g: 5.0,
        saturated_fat_g: 1.2,
        sodium_mg: 550,
        protein_g: 8.5,
        fiber_g: 8.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Special K Original',
      category: 'cereals',
      brand: "Kellogg's",
      image_url: null,
      nutrition: {
        energy_kcal: 379,
        sugars_g: 15.0,
        saturated_fat_g: 0.5,
        sodium_mg: 600,
        protein_g: 14.0,
        fiber_g: 2.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Coco Pops',
      category: 'cereals',
      brand: "Kellogg's",
      image_url: null,
      nutrition: {
        energy_kcal: 387,
        sugars_g: 35.0,
        saturated_fat_g: 1.0,
        sodium_mg: 450,
        protein_g: 5.0,
        fiber_g: 2.0,
        fruits_veg_percent: 0,
      },
    },
  ],

  bread: [
    {
      product_name: 'Wooden Bakery Arabic Bread White',
      category: 'bread',
      brand: 'Wooden Bakery',
      image_url: null,
      nutrition: {
        energy_kcal: 275,
        sugars_g: 2.5,
        saturated_fat_g: 0.3,
        sodium_mg: 480,
        protein_g: 9.0,
        fiber_g: 3.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: "L'usine Sliced White Bread",
      category: 'bread',
      brand: "L'usine",
      image_url: null,
      nutrition: {
        energy_kcal: 265,
        sugars_g: 5.0,
        saturated_fat_g: 1.2,
        sodium_mg: 500,
        protein_g: 8.0,
        fiber_g: 2.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Bimbo Whole Wheat Bread',
      category: 'bread',
      brand: 'Bimbo',
      image_url: null,
      nutrition: {
        energy_kcal: 247,
        sugars_g: 4.0,
        saturated_fat_g: 0.6,
        sodium_mg: 450,
        protein_g: 10.0,
        fiber_g: 6.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: "L'usine Butter Croissant",
      category: 'bread',
      brand: "L'usine",
      image_url: null,
      nutrition: {
        energy_kcal: 414,
        sugars_g: 10.0,
        saturated_fat_g: 12.0,
        sodium_mg: 380,
        protein_g: 7.0,
        fiber_g: 1.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Americana Vegetable Samosa',
      category: 'bread',
      brand: 'Americana',
      image_url: null,
      nutrition: {
        energy_kcal: 290,
        sugars_g: 2.0,
        saturated_fat_g: 4.5,
        sodium_mg: 520,
        protein_g: 5.5,
        fiber_g: 2.0,
        fruits_veg_percent: 15,
      },
    },
    {
      product_name: "L'usine Chocolate Cake",
      category: 'bread',
      brand: "L'usine",
      image_url: null,
      nutrition: {
        energy_kcal: 420,
        sugars_g: 32.0,
        saturated_fat_g: 8.0,
        sodium_mg: 300,
        protein_g: 5.0,
        fiber_g: 2.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Wooden Bakery Whole Wheat Arabic Bread',
      category: 'bread',
      brand: 'Wooden Bakery',
      image_url: null,
      nutrition: {
        energy_kcal: 250,
        sugars_g: 2.0,
        saturated_fat_g: 0.4,
        sodium_mg: 460,
        protein_g: 11.0,
        fiber_g: 7.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Modern Bakery Brioche Roll',
      category: 'bread',
      brand: 'Modern Bakery',
      image_url: null,
      nutrition: {
        energy_kcal: 380,
        sugars_g: 12.0,
        saturated_fat_g: 6.0,
        sodium_mg: 380,
        protein_g: 8.0,
        fiber_g: 1.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Lebanese Mills Pita Bread',
      category: 'bread',
      brand: 'Lebanese Mills',
      image_url: null,
      nutrition: {
        energy_kcal: 270,
        sugars_g: 3.0,
        saturated_fat_g: 0.5,
        sodium_mg: 480,
        protein_g: 9.0,
        fiber_g: 3.0,
        fruits_veg_percent: 0,
      },
    },
  ],

  meat: [
    {
      product_name: 'Al Islami Chicken Breast',
      category: 'meat',
      brand: 'Al Islami',
      image_url: null,
      nutrition: {
        energy_kcal: 110,
        sugars_g: 0,
        saturated_fat_g: 0.5,
        sodium_mg: 65,
        protein_g: 23.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Kabeer Beef Burger',
      category: 'meat',
      brand: 'Al Kabeer',
      image_url: null,
      nutrition: {
        energy_kcal: 250,
        sugars_g: 1.0,
        saturated_fat_g: 8.0,
        sodium_mg: 550,
        protein_g: 14.0,
        fiber_g: 0.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Sadia Chicken Nuggets',
      category: 'meat',
      brand: 'Sadia',
      image_url: null,
      nutrition: {
        energy_kcal: 260,
        sugars_g: 2.0,
        saturated_fat_g: 3.5,
        sodium_mg: 620,
        protein_g: 12.0,
        fiber_g: 1.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Areesh Chicken Sausage',
      category: 'meat',
      brand: 'Al Areesh',
      image_url: null,
      nutrition: {
        energy_kcal: 230,
        sugars_g: 1.5,
        saturated_fat_g: 5.0,
        sodium_mg: 700,
        protein_g: 13.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Farm Fresh Chicken Thigh',
      category: 'meat',
      brand: 'Farm Fresh',
      image_url: null,
      nutrition: {
        energy_kcal: 177,
        sugars_g: 0,
        saturated_fat_g: 3.0,
        sodium_mg: 75,
        protein_g: 18.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Americana Chicken Mortadella',
      category: 'meat',
      brand: 'Americana',
      image_url: null,
      nutrition: {
        energy_kcal: 215,
        sugars_g: 2.0,
        saturated_fat_g: 5.5,
        sodium_mg: 830,
        protein_g: 11.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Rawdah Premium Beef Mince',
      category: 'meat',
      brand: 'Al Rawdah',
      image_url: null,
      nutrition: {
        energy_kcal: 190,
        sugars_g: 0,
        saturated_fat_g: 5.0,
        sodium_mg: 70,
        protein_g: 21.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Islami Halal Lamb Kofta',
      category: 'meat',
      brand: 'Al Islami',
      image_url: null,
      nutrition: {
        energy_kcal: 235,
        sugars_g: 1.0,
        saturated_fat_g: 7.0,
        sodium_mg: 580,
        protein_g: 14.0,
        fiber_g: 0.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Tanmiah Fresh Chicken Breast',
      category: 'meat',
      brand: 'Tanmiah',
      image_url: null,
      // Source: USDA FDC 171052 (Chicken, broilers or fryers, meat only, raw)
      nutrition: {
        energy_kcal: 119,
        sugars_g: 0,
        saturated_fat_g: 0.8,
        sodium_mg: 77,
        protein_g: 21.4,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
  ],

  fruits: [
    {
      product_name: 'Del Monte Pineapple Chunks',
      category: 'fruits',
      brand: 'Del Monte',
      image_url: null,
      nutrition: {
        energy_kcal: 60,
        sugars_g: 14.0,
        saturated_fat_g: 0,
        sodium_mg: 10,
        protein_g: 0.3,
        fiber_g: 0.8,
        fruits_veg_percent: 65,
      },
    },
    {
      product_name: 'Dole Banana (fresh)',
      category: 'fruits',
      brand: 'Dole',
      image_url: null,
      nutrition: {
        energy_kcal: 89,
        sugars_g: 12.2,
        saturated_fat_g: 0.1,
        sodium_mg: 1,
        protein_g: 1.1,
        fiber_g: 2.6,
        fruits_veg_percent: 100,
      },
    },
    {
      product_name: 'Al Ain Tomato Paste',
      category: 'fruits',
      brand: 'Al Ain',
      image_url: null,
      nutrition: {
        energy_kcal: 82,
        sugars_g: 12.0,
        saturated_fat_g: 0.1,
        sodium_mg: 580,
        protein_g: 4.3,
        fiber_g: 4.0,
        fruits_veg_percent: 95,
      },
    },
    {
      product_name: 'Goody Green Peas (canned)',
      category: 'fruits',
      brand: 'Goody',
      image_url: null,
      nutrition: {
        energy_kcal: 68,
        sugars_g: 5.0,
        saturated_fat_g: 0.1,
        sodium_mg: 300,
        protein_g: 4.5,
        fiber_g: 4.5,
        fruits_veg_percent: 85,
      },
    },
    {
      product_name: 'California Garden Fava Beans',
      category: 'fruits',
      brand: 'California Garden',
      image_url: null,
      nutrition: {
        energy_kcal: 91,
        sugars_g: 1.0,
        saturated_fat_g: 0.1,
        sodium_mg: 450,
        protein_g: 6.7,
        fiber_g: 5.0,
        fruits_veg_percent: 80,
      },
    },
    {
      product_name: 'Fresh Apple',
      category: 'fruits',
      brand: 'Fresh',
      image_url: null,
      nutrition: {
        energy_kcal: 52,
        sugars_g: 10.4,
        saturated_fat_g: 0,
        sodium_mg: 1,
        protein_g: 0.3,
        fiber_g: 2.4,
        fruits_veg_percent: 100,
      },
    },
    {
      product_name: 'Fresh Orange',
      category: 'fruits',
      brand: 'Fresh',
      image_url: null,
      nutrition: {
        energy_kcal: 47,
        sugars_g: 9.4,
        saturated_fat_g: 0,
        sodium_mg: 0,
        protein_g: 0.9,
        fiber_g: 2.4,
        fruits_veg_percent: 100,
      },
    },
    {
      product_name: 'Fresh Mango',
      category: 'fruits',
      brand: 'Fresh',
      image_url: null,
      // Source: USDA FDC 169910 (Mangos, raw)
      nutrition: {
        energy_kcal: 60,
        sugars_g: 13.7,
        saturated_fat_g: 0.1,
        sodium_mg: 1,
        protein_g: 0.8,
        fiber_g: 1.6,
        fruits_veg_percent: 100,
      },
    },
    {
      product_name: 'Fresh Carrot',
      category: 'fruits',
      brand: 'Fresh',
      image_url: null,
      // Source: USDA FDC 170393 (Carrots, raw)
      nutrition: {
        energy_kcal: 41,
        sugars_g: 4.7,
        saturated_fat_g: 0,
        sodium_mg: 69,
        protein_g: 0.9,
        fiber_g: 2.8,
        fruits_veg_percent: 100,
      },
    },
    {
      product_name: 'Medjool Dates',
      category: 'fruits',
      brand: 'Bateel',
      image_url: null,
      // Source: USDA FDC 168191 (Dates, medjool)
      nutrition: {
        energy_kcal: 277,
        sugars_g: 66.5,
        saturated_fat_g: 0,
        sodium_mg: 1,
        protein_g: 1.8,
        fiber_g: 6.7,
        fruits_veg_percent: 100,
      },
    },
  ],

  frozen: [
    {
      product_name: 'McCain French Fries',
      category: 'frozen',
      brand: 'McCain',
      image_url: null,
      nutrition: {
        energy_kcal: 165,
        sugars_g: 0.5,
        saturated_fat_g: 0.8,
        sodium_mg: 280,
        protein_g: 2.5,
        fiber_g: 2.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Kabeer Chicken Shawarma',
      category: 'frozen',
      brand: 'Al Kabeer',
      image_url: null,
      nutrition: {
        energy_kcal: 195,
        sugars_g: 1.5,
        saturated_fat_g: 3.5,
        sodium_mg: 640,
        protein_g: 15.0,
        fiber_g: 0.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Sadia Chicken Strips',
      category: 'frozen',
      brand: 'Sadia',
      image_url: null,
      nutrition: {
        energy_kcal: 240,
        sugars_g: 2.0,
        saturated_fat_g: 2.5,
        sodium_mg: 580,
        protein_g: 14.0,
        fiber_g: 1.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Islami Beef Samosa',
      category: 'frozen',
      brand: 'Al Islami',
      image_url: null,
      nutrition: {
        energy_kcal: 245,
        sugars_g: 2.5,
        saturated_fat_g: 4.0,
        sodium_mg: 500,
        protein_g: 8.0,
        fiber_g: 1.5,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Baskin Robbins Vanilla Ice Cream',
      category: 'frozen',
      brand: 'Baskin Robbins',
      image_url: null,
      nutrition: {
        energy_kcal: 250,
        sugars_g: 25.0,
        saturated_fat_g: 10.0,
        sodium_mg: 90,
        protein_g: 4.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Magnum Classic Ice Cream Bar',
      category: 'frozen',
      brand: 'Magnum',
      image_url: null,
      nutrition: {
        energy_kcal: 300,
        sugars_g: 28.0,
        saturated_fat_g: 14.0,
        sodium_mg: 60,
        protein_g: 4.5,
        fiber_g: 1.0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Al Islami Mixed Frozen Vegetables',
      category: 'frozen',
      brand: 'Al Islami',
      image_url: null,
      nutrition: {
        energy_kcal: 60,
        sugars_g: 4.0,
        saturated_fat_g: 0.1,
        sodium_mg: 25,
        protein_g: 3.0,
        fiber_g: 4.0,
        fruits_veg_percent: 100,
      },
    },
    {
      product_name: 'Sadia Frozen Whole Chicken',
      category: 'frozen',
      brand: 'Sadia',
      image_url: null,
      nutrition: {
        energy_kcal: 195,
        sugars_g: 0,
        saturated_fat_g: 3.0,
        sodium_mg: 80,
        protein_g: 18.0,
        fiber_g: 0,
        fruits_veg_percent: 0,
      },
    },
    {
      product_name: 'Lulu Frozen Spinach',
      category: 'frozen',
      brand: 'Lulu',
      image_url: null,
      // Source: USDA FDC 169287 (Spinach, frozen, chopped or leaf, unprepared)
      nutrition: {
        energy_kcal: 29,
        sugars_g: 0.65,
        saturated_fat_g: 0.04,
        sodium_mg: 74,
        protein_g: 3.6,
        fiber_g: 2.9,
        fruits_veg_percent: 100,
      },
    },
  ],
}

export function getDemoProductCount(categoryId: string): number {
  return DEMO_PRODUCTS[categoryId]?.length ?? 0
}
